### ISSUE TITLE
Add support for PHP 7.2.29, 7.3.16, 7.4.4

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#139]
https://www.php.net/ChangeLog-7.php#PHP_7_2
https://www.php.net/ChangeLog-7.php#PHP_7_3
https://www.php.net/ChangeLog-7.php#PHP_7_4

**Comment by cyrille-sg** [comment]
The stack ubuntu-14 is requiring swift auth v2 (current: v3) that will be deprecated soon by OVH. Can we just release the new php version on the ubuntu-18 stack and add in the changelog a line of notice about the ubuntu-14 stack, given the ongoing process of deprecated ubuntu-14?

**Comment by EtienneM** [comment]
You should be able to update PHP 7.2 and 7.3 on the scalingo-14 stack without trouble, can't you? 

scalingo-14 is in the process of being deprecated. The process takes several months hence we keep supporting it for now. It will be deprecated at the beginning of June.

**Comment by Soulou** [comment]
@EtienneM the swift client of Ubuntu 14.04 is not compatible with keystone API V3 and V2 will be deprovisioned

**Comment by EtienneM** [comment]
Yes I understand. As you stated, it "will be deprovisioned": it's working now and by the time we remove support for scalingo-14 it will probably still be working. Hence, as long as we can provide support for latest PHP version, we should do it. We didn't dropped scalingo-14 support yet.

**Comment by Soulou** [comment]
Ok got it, let's do it until it doesn't work for real

**Comment by Soulou** [comment]
I'm building scalingo-14 packages, but `7.4.4` doesn't build (configure fails)

```
checking whether to enable JIS-mapped Japanese font support in GD... no
checking for fabsf... yes
checking for floorf... yes
checking for zlib... yes
checking for libpng... yes
checking for libjpeg... no
configure: error: Package requirements (libjpeg) were not met:

No package 'libjpeg' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JPEG_CFLAGS
and JPEG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
tar (child): /tmp/php_e46q/package/php-7.4.4.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
./
```

@EtienneM  an Idea as you built the previous ones

**Comment by EtienneM** [comment]
PHP 7.4 never worked for scalingo-14 :)

**Comment by cyrille-sg** [comment]
Should we also update this page to mention 7.4 https://scalingo.com/technologies/php-hosting ?

**Comment by cyrille-sg** [comment]
Ticket opened: https://github.com/Scalingo/homepage/issues/998

**Comment by cyrille-sg** [comment]
Issue workflow completed
