### ISSUE TITLE
Upgrade from 7.4.4 to 7.4.9, 7.3.16 to 7.3.21, 7.2.29 to 7.2.33

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#145]
https://www.php.net/ChangeLog-7.php#7.2.30
https://www.php.net/ChangeLog-7.php#7.3.17
https://www.php.net/ChangeLog-7.php#7.4.5

**Comment by EtienneM** [comment]
https://www.php.net/ChangeLog-7.php#7.2.31
https://www.php.net/ChangeLog-7.php#7.3.19
https://www.php.net/ChangeLog-7.php#7.4.7

**Comment by Soulou** [comment]
Branch 7.x done

**Comment by Soulou** [comment]
Branch 7.3 done

**Comment by Soulou** [comment]
Branch 7.2 done

**Comment by EtienneM** [comment]
Thanks! :)
