### ISSUE TITLE
Add mcrypt to the list of availbale extensions

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#160]
PR #63 removed automatic build of mcrypt as it's not included anymore in PHP since 7.2. But we didn't compiled it for 7.4 apparently.

mcrypt deprecation embedded in PHP: https://www.php.net/manual/en/intro.mcrypt.php
PECL package: https://pecl.php.net/package/mcrypt

Notify when done: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700007259

**Comment by Soulou** [comment]
@EtienneM it seems we've already added PECL support https://github.com/Scalingo/php-buildpack/blob/master/support/ext/mcrypt

**Comment by EtienneM** [comment]
Yep I noticed, I think we forgot to compile it for 7.4. I tried to use it with a PHP 7.4 app and it apparently didn't work. We need to dig futher. The documentation at least needs to be updated :)

**Comment by Soulou** [comment]
Just ran it following our guide:

```
./package_ext mcrypt mcrypt 7.4
[...]
./
./etc/
./etc/conf.d/
./etc/conf.d/mcrypt.ini
./lib/
./lib/php/
./lib/php/extensions/
./lib/php/extensions/no-debug-non-zts-20190902/
./lib/php/extensions/no-debug-non-zts-20190902/mcrypt.so
/tmp/phpmcrypt_687l
scalingo-18/package/ext/20190902/php-mcrypt.tgz
-----> Creating checksum for ext/20190902/php-mcrypt
scalingo-18/package/ext/20190902/php-mcrypt.tgz [auth 0.534s, headers 0.846s, total 0.857s, 0.229 MB/s]
scalingo-18/package/ext/20190902/php-mcrypt.md5
```

**Comment by EtienneM** [comment]
Yes indeed, it works :+1:
