### ISSUE TITLE
Available PHP and Nginx Versions file is Not Accessible

### ISSUE THREAD

**Issue by dubcanada** [Scalingo/php-buildpack#17]

**Comment by Soulou** [comment]
curl https://lb1047.pcs.ovh.net/v1/AUTH_c91a9132e4f149809d23b20b6de57161/appsdeck-buildpack-php/manifest.php
curl https://lb1047.pcs.ovh.net/v1/AUTH_c91a9132e4f149809d23b20b6de57161/appsdeck-buildpack-php/manifest.nginx

Are you speaking of these files ?

**Comment by dubcanada** [comment]
The two

Available versions

Available PHP Versions Available NGINX Versions

I get a

Unauthorized

This server could not verify that you are authorized to access the document you requested.

For https://lb1047.pcs.ovh.net/v1/AUTH_c91a9132e4f149809d23b20b6de57161/appdeck-buildpack-php/manifest.php

It seems to be missing the s in appSdeck
