### ISSUE TITLE
Add swoole extension

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/php-buildpack#181]
This was required by a user on the support.

Swoole is an asynchronous library used by some PHP applications: https://www.php.net/manual/en/book.swoole.php

Contact https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700012849 when done

**Comment by Soulou** [comment]
For context: not an official extension, Heroku doesn't have it either: https://github.com/heroku/heroku-buildpack-php/issues/297

**Comment by johnsudaar** [comment]
This extension is needed by this project: https://shlink.io/

**Comment by tillkruss** [comment]
@Soulou: Feel free to submit a PR here: https://github.com/cachewerk/heroku-php-extensions

**Comment by johnsudaar** [comment]
It's also needed by Laravel Octane

Contact https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700058627 when done

**Comment by Frzk** [comment]
According to my tests, it works by just specifying:
```json
{
    "require": {
        "ext-swoole": "*"
    }
}
```
in `composer.json`. Successfully tested with `scalingo-22` and PHP `8.1.23` and `8.2.10`.

I guess this is the consequence of https://github.com/Scalingo/php-buildpack/pull/286

I think we can close this now. Please re-open an issue if need be.
