### ISSUE TITLE
[PHP 8] Add support for extension GMP

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#189]
When working on PHP 8 integration (https://github.com/Scalingo/php-buildpack/pull/185), @Soulou mentioned GMP extension is not compatible with PHP 8. 

However a customer reported he made GMP (6.2.0) work with PHP 8 on his local environment. We should investigate how to make this extension work.
https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700023003

**Comment by Soulou** [comment]
Acutally GMP after rebuilding all the assets (OVH incident) with the new GMP version, the GMP extension has been built with success, closing here
