### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by cphubs** [Scalingo/php-buildpack#19]
Hi
I push app but 502 error occured!
no container created for this app!

When i use heroku php buildpack with apache every thing is ok but when use NGINX in heroku and Scaling this error occured.

{
 
  "extra": {
    "paas": {
      "document-root": "public_html",
      "index-document": "index.php",
      "engines": {
        "nginx": "default",
        "php": "default"
      },
      "php-config": [],
      "php-includes": [],
      "nginx-includes": [],
     

 "log-files": [],
      "compile": [],
      "new-relic": false
    }
  }
}

in heroku php buildpack when i remove public_html everything work correctly

**Comment by Soulou** [comment]
Could I have more details about your error? The elements you've  given are not enough to identify the source. Please join the deployment logs. If you've any issue deploying on Scalingo, please contact support [at] scalingo.com and give additional details like your username and the name of the app.

Thank you very much, Best regards.

**Comment by cphubs** [comment]
when i create DOCUMENT_ROOT environment variable or set ("document-root": "public_html",) 502 error occured
