### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cphubs** [Scalingo/php-buildpack#20]
remote:
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now

i use 

"engines": {
        "php": "5.3.23",
        "nginx": "1.3.14"
      },

**Comment by Soulou** [comment]
As stated in the readme, versions supported are: "Nginx 1.5 and 1.6 - PHP 5.3, 5.4, 5.5 and 5.6 - PHP FPM"

So the version of nginx you're requesting is not available. please use a more up-to-date version. (Last stable is 1.6.2)
