### ISSUE TITLE
error php version smaller than 5.4

### ISSUE THREAD

**Issue by amirarabi** [Scalingo/php-buildpack#21]
Supported PHP versions are: 5.6.8 5.6.7 5.6.6 5.6.5 5.6.4 5.5.24 5.5.23 5.5.22 5.5.21 5.5.20 5.4.40 5.4.39 5.4.38 5.4.37 5.4.36 5.3.28

smaller than 5.5.20 this error occured! 

-----> Using u1000 to run an application
-----> Fetching custom buildpack
-----> PHP (composer.json) app detected
-----> Bundling NGINX 1.6.3
       Checksums match. Fetching from cache.
-----> Bundling PHP 5.4.40
-----> Bundling extensions
       apcu
       Checksums match. Fetching from cache.
remote:
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
To dokku@********.tk:sample8
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@*******.tk:sample8'

**Comment by Soulou** [comment]
You're right, actually it concerns only the PHP 5.4.x versions, there are no issues with 5.3, 5.5 and 5.6, I'm going to fix this now.

**Comment by Soulou** [comment]
Done, you should not have this issue anymore, PHP third-party extension have been uploaded to CDN.
