### ISSUE TITLE
Cannot deploy on scalingo, BuildPack Error

### ISSUE THREAD

**Issue by Krilline** [Scalingo/php-buildpack#216]
Hello,

I'm currently having issues deploying on Scalingo, it comes from the php-buildpack, tried deploying multiple times, different errors occur:

```bash
tar (child): /tmp/cache/package/libwebp-1.2.1.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2 
tar: Error is not recoverable: exiting now 
 ! An error occurred during buildpack compilation 
 ! Error deploying the application
 ! → Invalid return code from buildpack
```

```bash
tar (child): /tmp/cache/package/libonig-6.9.7.1.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
 !     An error occurred during buildpack compilation
 !   Error deploying the application
 !   → Invalid return code from buildpack 
```
Could you help me with that please ?

Thanks in advance,

**Comment by EtienneM** [comment]
Hi,

Indeed the PR https://github.com/Scalingo/php-buildpack/pull/215 introduced this issue. We just uploaded the missing version for these libs. Your deployment should be good now. Can you please retry the deployment and let us now if it's OK for you?

**Comment by Krilline** [comment]
It's working now ! Thank you 👍

**Comment by EtienneM** [comment]
Sorry for the inconvenience, I wish you a pleasant day

**Comment by DeadAvatar** [comment]
Still same issue for me

**Comment by EtienneM** [comment]
Hi,

Can you contact our support team, either on the embedded chat or by email at support@scalingo.com?
