### ISSUE TITLE
 [PHP] Upgrade from 7.3.31 to 7.3.33, 7.4.25 to 7.4.26 and 8.0.12 to 8.0.13, and release 8.1.0

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#222]
Notify when 8.1 is available:
- https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700053054

**Comment by Soulou** [comment]
8.0.12 contains a CVE fix: https://bugs.php.net/bug.php?id=81026

**Comment by EtienneM** [comment]
Raising the priority to `high`  in order to handle the release of the new major version 8.1.0 as early as possible.
