### ISSUE TITLE
[PECL Extension] Support all PECL extensions

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#249]
Implement the same thing as done in https://github.com/Scalingo/php-buildpack/pull/244, but allow any extension name. The extension name should come from the `require.ext-*` section of the composer.json

**Comment by Frzk** [comment]
I took a look at the extensions listed on the PECL website (https://pecl.php.net/packages.php).
As you can see, there are many... and some are really old. For example, in the first category (`Authentication`) we have:
- `courrierauth`, last update 2006-12
- `krb5`, last update 2020-09
- `PAM`, last update 2022-01
- `radius`, last update 2016-02 (both stable and beta)
- `sasl`, last update 2004-01.

I don't really know if we want to support extensions that are that old. Although they are maybe still relevant and working well, I **personally** try to avoid using old software like this, unless there are no other choice.

So my question is: do we really want to support all these extensions or should we rather make a selection out of a list, considering some criteria such as last update date, usefulness (`selinux`?, `tk`? `win32std`?, `libvirt`?...) , harm potential, code review, ... ?

**Comment by EtienneM** [comment]
> So my question is: do we really want to support all these extensions or should we rather make a selection out of a list, considering some criteria such as last update date, usefulness (`selinux`?, `tk`? `win32std`?, `libvirt`?...) , harm potential, code review, ... ?

We already support an allow list of PECL extension such as:

https://github.com/Scalingo/php-buildpack/blob/b4f7069056dd4961b419fbe287cce1e0d8ac67e0/support/ext/event#L14-L16

The idea of this issue is to make a generic support of any PECL extension so that customers use the extension they want / need. Hence, trusting them to only install _good_ extensions. I mean, it's not that different than trusting them to choose the good Node.js extensions for their app for Node.js apps, don't you think?

**Comment by benjaminach** [comment]
Hello @EtienneM, is it possible to have a rough estimate of this item?
Is there a way to narrow the scope of this item to ship it faster?

Context: one customer is asking for the support of the OCI8 extension for PHP8+.

**Comment by EtienneM** [comment]
No I don't have my head in this project right now so I don't have any idea. But that shouldn't be too complicated to do. Most pipes are already there.
