### ISSUE TITLE
[Composer] Upgrade from 2.2.12 to 2.2.18, 2.3.5 to 2.3.10 and 2.4.2

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#254]
https://github.com/composer/composer/releases/tag/2.2.13

**Comment by EtienneM** [comment]
https://github.com/composer/composer/releases/tag/2.3.6

**Comment by EtienneM** [comment]
https://github.com/composer/composer/releases/tag/2.2.14
https://github.com/composer/composer/releases/tag/2.3.7

**Comment by EtienneM** [comment]
https://github.com/composer/composer/releases/tag/2.2.15
https://github.com/composer/composer/releases/tag/2.3.8

**Comment by EtienneM** [comment]
https://github.com/composer/composer/releases/tag/2.2.16
https://github.com/composer/composer/releases/tag/2.2.17

https://github.com/composer/composer/releases/tag/2.3.9
https://github.com/composer/composer/releases/tag/2.3.10

**Comment by EtienneM** [comment]
https://github.com/composer/composer/releases/tag/2.4.0
Release highlights: https://blog.packagist.com/composer-2-4/

**Comment by EtienneM** [comment]
https://github.com/composer/composer/releases/tag/2.2.18
https://github.com/composer/composer/releases/tag/2.4.1

**Comment by Frzk** [comment]
Closed by https://github.com/Scalingo/documentation/pull/1751
