### ISSUE TITLE
Support AMQP PECL extension

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/php-buildpack#258]
Asked on the support
Conv: https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700075996

**Comment by johnsudaar** [comment]
It's not just a simple download from the PECL registry. Since this extension needs the librabbitmq that is not installed on the default stack.

**Comment by curzolapierre** [comment]
May be useful links:
On PECL documentation, the amqp page: https://pecl.php.net/package/amqp
Amqp repository: https://github.com/php-amqp/php-amqp#installation
