### ISSUE TITLE
Extension not found on pecl.php.net error 404

### ISSUE THREAD

**Issue by potsky** [Scalingo/php-buildpack#297]
Hi !

Since commit https://github.com/Scalingo/php-buildpack/commit/86d46cb25e7002811085ae71409008f66789fa2a we cannot deploy our app as usual.

This is not really an issue because we have found a fix but perhaps the build pack could be improved.

In `composer.json`, we used to load `ext-simplexml`. The deploy now runs successfully by replacing this package by `ext-SimpleXML`.

In the function below perhaps we could add `-I` in the `grep` function:

```shell
function is_embedded_extension() {
  local extension_name="${1}"

  if php --modules | grep --quiet "${extension_name}" ; then
    echo "true"
  else
    echo "false"
  fi
}
```

From a one-off dyno, we have:

```shell
[16:20][osc-fr1] Scalingo ~ $ php --modules
[PHP Modules]
apcu
bcmath
bz2
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
imagick
intl
json
libxml
mbstring
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

and so it could occurs for other customers with other packages.

Cheers :beers:

**Comment by Soulou** [comment]
@potsky indeed module names are not consistent, case is now ignored, it should work as expected again
