### ISSUE TITLE
Buildpack for recent version of PHP 5.6

### ISSUE THREAD

**Issue by justine** [Scalingo/php-buildpack#30]
Today, when we specify PHP version "5.6.*" in a composer.json file, the PHP version installed is 5.6.9
The last version of PHP 5.6 is 5.6.30 (jan 2017) and it will be great to have it on my Scalingo apps.

**Comment by Soulou** [comment]
Actually 5.6.30 is available also, can you try the syntax `~5.6` or specifying `5.6.30` entirely?

All versions of PHP should be present from 5.4 to 7.1

**Comment by justine** [comment]
The syntax ~5.6 throws an error when deploying the app:
<-- Start deployment of vault-preprod -->
 !     PHP version ~5.6 is not supported.
 !     Supported versions are: 7.1.2 7.1.1 7.1.0 7.0.16 7.0.15 7.0.14 7.0.13 7.0.12 7.0.11 7.0.10 7.0.9 7.0.8 7.0.7 7.0.6 7.0.5 7.0.4 7.0.3 7.0.2 7.0.1 7.0.0 5.6.30 5.6.29 5.6.28 5.6.27 5.6.26 5.6.25 5.6.24 5.6.23 5.6.22 5.6.21 5.6.20 5.6.19 5.6.18 5.6.17 5.6.16 5.6.15 5.6.14 5.6.13 5.6.12 5.6.11 5.6.10 5.6.9 5.6.8 5.6.7 5.6.6 5.6.5 5.6.4 5.5.38 5.5.37 5.5.36 5.5.35 5.5.34 5.5.33 5.5.32 5.5.31 5.5.30 5.5.29 5.5.28 5.5.27 5.5.26 5.5.25 5.5.24 5.5.23 5.5.22 5.5.21 5.5.20 5.4.45 5.4.40 5.4.39 5.4.38 5.4.37 5.4.36 5.3.29 5.3.28
 !     An error occured during buildpack compilation
 !   Error deploying the application
 !   → Invalid return code from buildpack

Both syntax 5.6.* and ~5.6 should work in composer file.

Explicit specification of 5.6.30 works.

**Comment by Soulou** [comment]
Are you defining the the PHP version in the `.extra.paas.engines.php` section? (just to be sure)

**Comment by justine** [comment]
Yes, we define it like this:
{
      ...
      "extra": {
            "paas": {
                  "engines": {
                        "php": "5.6.*",
                  },
                  ...
             }
      }
}
