### ISSUE TITLE
composers's `--optimize-autoloader`

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/php-buildpack#310]
According to the docs, you're currently running `composer install --no-dev` for all Laravel apps. Adding this argument should significantly improve performance and it also the recommended why by Laravel: https://laravel.com/docs/10.x/deployment#autoloader-optimization

**Comment by EtienneM** [comment]
This is already what is done: 

https://github.com/Scalingo/php-buildpack/blob/efe5e3baa49c99fc25537dd427ddb0341593b424/lib/composer#L125-L127

**Comment by EtienneM** [comment]
You are right, I opened a ticket to update our documentation.
