### ISSUE TITLE
Extension excimer

### ISSUE THREAD

**Issue by potsky** [Scalingo/php-buildpack#312]
Hello !

We would like to install excimer to profile in Sentry : https://docs.sentry.io/platforms/php/guides/laravel/profiling/

We have added `php-excimer` in our `Aptfile` but we cannot find how to enable the extension. Running `phpenmod -s fpm excimer` is not possible because the script is located at `/app/.apt/usr/sbin/phpenmod` but it sources `/usr/sbin/php-helper` which does not exist of course.

Does it need to be part of the `php-buildpack` ? Or can we load the module in an other way in `composer.json:pass` for example?

**Comment by Frzk** [comment]
Hello,

You should be able to add the Excimer extension by putting the dependency in your `composer.json` file, like so:

```json
{
    "require": {
        "ext-excimer": "*"
    }
}
```

Don't forget to rebuild your `composer.lock` file:
```bash
composer update --ignore-platform-req=ext-excimer
```

And you should be good to go!
Please keep us updated :)
