### ISSUE TITLE
PECL OCI installation failure

### ISSUE THREAD

**Issue by SCedricThomas** [Scalingo/php-buildpack#429]
[This customer](https://app.intercom.com/a/inbox/w4oogu7s/inbox/admin/5751062/conversation/12375700238580?view=List) is facing an issue during the PECL OCI extension

![image](https://github.com/Scalingo/php-buildpack/assets/112880007/5fc46488-4e68-40e2-853f-829ff298d0a6)

**Comment by Frzk** [comment]
![image](https://github.com/Scalingo/php-buildpack/assets/5741555/1bba294d-7a35-46fe-a878-c8c3f63ea326)
