### ISSUE TITLE
composer_extra_key seems to be undefined in project having a composer.json

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#54]
Here is the output of a git push. Reproduced with two projects using a composer.json. Notice the error after "Fetching deployment cache".

```
$ git push scalingo master --force
Enumerating objects: 22, done.
Counting objects: 100% (22/22), done.
Delta compression using up to 4 threads
Compressing objects: 100% (17/17), done.
Writing objects: 100% (22/22), 3.99 KiB | 511.00 KiB/s, done.
Total 22 (delta 4), reused 12 (delta 0)
 <-- Start deployment of etienne-support -->
       Fetching source code
       Fetching deployment cache
error: syntax error, unexpected .., expecting $end
.extra..engines.php // ""      1 compile error
-----> Bundling NGINX 1.10.1
...
```

**Comment by Soulou** [comment]
Fixed by https://github.com/Scalingo/php-buildpack/commit/21c9ac677cd98f7c721896c0ea973600360984ee

I wasn't a critical issue as it was only when checking PHP version that this error happened, so the key .extra.paas.engines.php was not working, but all the rest was OK
