### ISSUE TITLE
Deprecate the nonode branch

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/php-buildpack#91]
Related to the discussion [here](https://github.com/Scalingo/php-buildpack/pull/90#issuecomment-501336378). 

The nonode branch should be deprecated in favor of the environment variable `PHP_BUILDPACK_NO_NODE`.

**Comment by Soulou** [comment]
Fixed by ea5fdc3

I'm not breaking the build

Eventually the build will fail in the future, the person will look its log and see this. Not a problem that they keep using it for now.
